### PR TITLE
Fix chromedriver errors

### LINKED ISSUE #70: Getting an error
DevTools listening on ws://127.0.0.1:49693/devtools/browser/b2c4ae59-d7a4-4479-991b-af48f9f907bd
Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "LinkedInDL.py", line 397, in downloader
  File "site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 80

I am getting this error. What can I do?

### LINKED ISSUE #71: error
crhrome driver loads and crashes immediately.

DevTools listening on ws://127.0.0.1:52253/devtools/browser/670ca79a-00fb-4325-984b-912151a3bed8
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "LinkedDL.py", line 340, in downloader
  File "site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 85

this is for the latest version

### LINKED ISSUE #73: Download doesn't start due to different chromedrive.exe version
Hi,
When trying to use the Windows executable, with all information provided to the GUI Loader, download just hangs-up and doesn't starts. 
After stopping the process, there is displayed a report saying that the chromedriver.exe supported is release 80, whereas, in my case I have installed Chrome release 85.
Is there any way to reconcile this matter?
Note that "brute force"(a chromerdriver.exe release 85) is not working as the program just doesn't starts at all.
Likely we will have more and more browser releases coming out and therefore I am (just) asking if there is any possibility to automatically keep the GUI loader using the Chrome Driver installed on the machine.
Attached is a screenshot with the error from the app.

Annotation 2020-08-03 174116

Thanks.

### LINKED ISSUE #75: chromedriver not supported
LD LLD

### PR DESCRIPTION
**Pull request by adegeofroy-exeter**
fixes #75, fixes #73, fixes #71, fixes #70

### CODE REVIEW

**Comment by adegeofroy-exeter** [comment]
Closed by mistake.

**Comment by lensbreak** [comment]
@r00tmebaby @adegeofroy-exeter
When is the pull request going to be merged? Or at least can you tell us how to execute the new version where you fixed the chromedriver problem? How to compile the py script into executable exe so it can be used with the UI?

**Comment by clivejordan** [comment]
Any update on merging this Pull Request?

**Comment by r00tmebaby** [comment]
Sorry for being away for a while. Was working on many other projects and also study, did not have any time and desire to have look at this release. I will do my best to read all issues and come up with solutions whenever have some free time.

Regards

**Pull request merged**
